version: '3.9'

services:
  backend:
    build: ./backend
    container_name: raingauge-backend 
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: raingauge-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
